Style/FrozenStringLiteralComment:
  Enabled: false
Naming/FileName:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false